### 2D Numpy in Python

#### Create a 2D numpy Array

In [107]:
# Import the libraries 

import numpy as np

Consider the list <code>a</code>, which contains three nested lists <b>each of equal size</b>.

In [109]:
# Create a list 

a = [[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

We can cast the list to a Numpy Array as follows:

In [111]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

We can use the attribute <code>ndim</code> to obtain the number of axes or dimensions, referred to ask the rank.

In [113]:
# Show the numpy array dimensions
A.ndim

2

Attribute <code>shape</code> returns a tuple corresponding to the sixe or number of each dimension.

In [115]:
# Shoe the numpy array shape

A.shape

(3, 3)

The total number of elements in te array is given by the attribute <code>size</code>.

In [117]:
# Show the numpy array size

A.size

9

#### Accessing different elements ot a Numpy Array

We can use rectangular brackets to access the different elements to the array.

We simply use the swuare brakcets and the indices corresponding to the element we would like:

In [119]:
# Acces the element on the second row and third column

A[1,2]

23

We can also use the following notation to obtain the elements:

In [121]:
A[1][2]

23

We can also use slicing in numpy arrays. This can be done with the following syntax:

In [123]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

Similary, we can obtain the first two rows of the 3rd columns as follows:

In [125]:
# Access the element on the first and second rows and third column

A[0:2,2]

array([13, 23])

#### Basic Operations

We can also add arrats. The process is identical to matrix addition.

The Numpy array is given by <code>X</code> and <code>Y</code>

In [128]:
# Create a numpy array X

X = np.array([[1,0],[0,1]])
X

array([[1, 0],
       [0, 1]])

In [129]:
# Create a numpy array Y

Y = np.array([[2,1],[1,2]])
Y

array([[2, 1],
       [1, 2]])

We can add the numpy array as follows.

In [131]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplying a numpy array by scaler is identical yo multiplying a matrix by a scaler. We can perform the operation as follows.

In [133]:
# Create a Numpy array Y

Y = np.array([[2,1],[1,2]])
Y

array([[2, 1],
       [1, 2]])

In [134]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position. We can perform element-wise product of the array <code>X</code> and <code>Y</code> as follows:

In [136]:
# Create a Numpy array Y

Y = np.array([[2,1],[1,2]])
Y

array([[2, 1],
       [1, 2]])

In [137]:
# Create a Numpy array X 

X = np.array([[1,0],[0,1]])
X

array([[1, 0],
       [0, 1]])

In [138]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication woth the numpy arrays <code>A</code> and <code>B</code> as follows:

First, we define matrix <code>A</code> and <code>B</code>:

In [140]:
# Create a matrix A

A = np.array([[0,1,1],[1,0,1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [141]:
# Create a matrix B

B = np.array([[1,1],[1,1],[-1,1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function <code>dot</code> to multiply the arrays together.

In [143]:
# Calculate the dot product
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [144]:
# Calculate the sine of Z
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

We use the numpy attribute <code>T</code> to calculate the transposed matrix

In [146]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [147]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

#### Quiz on 2D Numpy Array 

Consider the following list <code>a</code>, convert it to a Numpy Array.

In [149]:
# Write your code below and press Shif+Enter to execute

A = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [156]:
A = np.array(A)

Calculate the numpy array size

In [158]:
A.size

12

Access the element on the first row and first and second columns

In [163]:
A[0][0:2]

array([1, 2])

Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>

In [168]:
B = np.array([[0,1],[1,0],[1,1],[-1,0 ]])

np.dot(A,B)

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])